//  Defines the syntax for the protocol buffer code

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.1
// source: domain/hospital/proto/hospital.proto

//  Declares the package in use. This prevents naming conflict between different projects

package hospital

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [Response] Get hospital list
type HospitalListProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hospitals []*HospitalProto `protobuf:"bytes,1,rep,name=hospitals,proto3" json:"hospitals,omitempty"`
}

func (x *HospitalListProto) Reset() {
	*x = HospitalListProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_hospital_proto_hospital_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HospitalListProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HospitalListProto) ProtoMessage() {}

func (x *HospitalListProto) ProtoReflect() protoreflect.Message {
	mi := &file_domain_hospital_proto_hospital_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HospitalListProto.ProtoReflect.Descriptor instead.
func (*HospitalListProto) Descriptor() ([]byte, []int) {
	return file_domain_hospital_proto_hospital_proto_rawDescGZIP(), []int{0}
}

func (x *HospitalListProto) GetHospitals() []*HospitalProto {
	if x != nil {
		return x.Hospitals
	}
	return nil
}

// [Respon] Get Hospital
type HospitalProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HealthcareId   string                 `protobuf:"bytes,1,opt,name=healthcare_id,json=healthcareId,proto3" json:"healthcare_id,omitempty"`
	HealthcareName string                 `protobuf:"bytes,2,opt,name=healthcare_name,json=healthcareName,proto3" json:"healthcare_name,omitempty"`
	IsActive       bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	UserCreate     string                 `protobuf:"bytes,4,opt,name=user_create,json=userCreate,proto3" json:"user_create,omitempty"`
	CreateAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
}

func (x *HospitalProto) Reset() {
	*x = HospitalProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_hospital_proto_hospital_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HospitalProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HospitalProto) ProtoMessage() {}

func (x *HospitalProto) ProtoReflect() protoreflect.Message {
	mi := &file_domain_hospital_proto_hospital_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HospitalProto.ProtoReflect.Descriptor instead.
func (*HospitalProto) Descriptor() ([]byte, []int) {
	return file_domain_hospital_proto_hospital_proto_rawDescGZIP(), []int{1}
}

func (x *HospitalProto) GetHealthcareId() string {
	if x != nil {
		return x.HealthcareId
	}
	return ""
}

func (x *HospitalProto) GetHealthcareName() string {
	if x != nil {
		return x.HealthcareName
	}
	return ""
}

func (x *HospitalProto) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *HospitalProto) GetUserCreate() string {
	if x != nil {
		return x.UserCreate
	}
	return ""
}

func (x *HospitalProto) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

// Get Hospital based on Healthcare ID
type HospitalGetProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HealthcareId string `protobuf:"bytes,1,opt,name=healthcare_id,json=healthcareId,proto3" json:"healthcare_id,omitempty"`
}

func (x *HospitalGetProto) Reset() {
	*x = HospitalGetProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_hospital_proto_hospital_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HospitalGetProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HospitalGetProto) ProtoMessage() {}

func (x *HospitalGetProto) ProtoReflect() protoreflect.Message {
	mi := &file_domain_hospital_proto_hospital_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HospitalGetProto.ProtoReflect.Descriptor instead.
func (*HospitalGetProto) Descriptor() ([]byte, []int) {
	return file_domain_hospital_proto_hospital_proto_rawDescGZIP(), []int{2}
}

func (x *HospitalGetProto) GetHealthcareId() string {
	if x != nil {
		return x.HealthcareId
	}
	return ""
}

// Add hospital
type HospitalAddProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addhospital *HospitalProto `protobuf:"bytes,1,opt,name=addhospital,proto3" json:"addhospital,omitempty"`
}

func (x *HospitalAddProto) Reset() {
	*x = HospitalAddProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_hospital_proto_hospital_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HospitalAddProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HospitalAddProto) ProtoMessage() {}

func (x *HospitalAddProto) ProtoReflect() protoreflect.Message {
	mi := &file_domain_hospital_proto_hospital_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HospitalAddProto.ProtoReflect.Descriptor instead.
func (*HospitalAddProto) Descriptor() ([]byte, []int) {
	return file_domain_hospital_proto_hospital_proto_rawDescGZIP(), []int{3}
}

func (x *HospitalAddProto) GetAddhospital() *HospitalProto {
	if x != nil {
		return x.Addhospital
	}
	return nil
}

var File_domain_hospital_proto_hospital_proto protoreflect.FileDescriptor

var file_domain_hospital_proto_hospital_proto_rawDesc = []byte{
	0x0a, 0x24, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a,
	0x0a, 0x11, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x35, 0x0a, 0x09, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61,
	0x6c, 0x2e, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x09, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x73, 0x22, 0xd4, 0x01, 0x0a, 0x0d, 0x48,
	0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x0a, 0x0d,
	0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x61, 0x72, 0x65, 0x49,
	0x64, 0x12, 0x27, 0x0a, 0x0f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x61, 0x72, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x68, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x63, 0x61, 0x72, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73,
	0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x73,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x74, 0x22, 0x37, 0x0a, 0x10, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63,
	0x61, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x63, 0x61, 0x72, 0x65, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x10, 0x48, 0x6f,
	0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x39,
	0x0a, 0x0b, 0x61, 0x64, 0x64, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x48,
	0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0b, 0x61, 0x64,
	0x64, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x32, 0xcc, 0x01, 0x0a, 0x0f, 0x48, 0x6f,
	0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e,
	0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61,
	0x6c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x03,
	0x47, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x48,
	0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x17, 0x2e, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x48, 0x6f, 0x73, 0x70, 0x69,
	0x74, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x03, 0x41, 0x64,
	0x64, 0x12, 0x1a, 0x2e, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x48, 0x6f, 0x73,
	0x70, 0x69, 0x74, 0x61, 0x6c, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x2e,
	0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61,
	0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_domain_hospital_proto_hospital_proto_rawDescOnce sync.Once
	file_domain_hospital_proto_hospital_proto_rawDescData = file_domain_hospital_proto_hospital_proto_rawDesc
)

func file_domain_hospital_proto_hospital_proto_rawDescGZIP() []byte {
	file_domain_hospital_proto_hospital_proto_rawDescOnce.Do(func() {
		file_domain_hospital_proto_hospital_proto_rawDescData = protoimpl.X.CompressGZIP(file_domain_hospital_proto_hospital_proto_rawDescData)
	})
	return file_domain_hospital_proto_hospital_proto_rawDescData
}

var file_domain_hospital_proto_hospital_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_domain_hospital_proto_hospital_proto_goTypes = []interface{}{
	(*HospitalListProto)(nil),     // 0: hospital.HospitalListProto
	(*HospitalProto)(nil),         // 1: hospital.HospitalProto
	(*HospitalGetProto)(nil),      // 2: hospital.HospitalGetProto
	(*HospitalAddProto)(nil),      // 3: hospital.HospitalAddProto
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_domain_hospital_proto_hospital_proto_depIdxs = []int32{
	1, // 0: hospital.HospitalListProto.hospitals:type_name -> hospital.HospitalProto
	4, // 1: hospital.HospitalProto.create_at:type_name -> google.protobuf.Timestamp
	1, // 2: hospital.HospitalAddProto.addhospital:type_name -> hospital.HospitalProto
	5, // 3: hospital.HospitalService.List:input_type -> google.protobuf.Empty
	2, // 4: hospital.HospitalService.Get:input_type -> hospital.HospitalGetProto
	3, // 5: hospital.HospitalService.Add:input_type -> hospital.HospitalAddProto
	0, // 6: hospital.HospitalService.List:output_type -> hospital.HospitalListProto
	1, // 7: hospital.HospitalService.Get:output_type -> hospital.HospitalProto
	1, // 8: hospital.HospitalService.Add:output_type -> hospital.HospitalProto
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_domain_hospital_proto_hospital_proto_init() }
func file_domain_hospital_proto_hospital_proto_init() {
	if File_domain_hospital_proto_hospital_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_domain_hospital_proto_hospital_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HospitalListProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_hospital_proto_hospital_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HospitalProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_hospital_proto_hospital_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HospitalGetProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_hospital_proto_hospital_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HospitalAddProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_domain_hospital_proto_hospital_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domain_hospital_proto_hospital_proto_goTypes,
		DependencyIndexes: file_domain_hospital_proto_hospital_proto_depIdxs,
		MessageInfos:      file_domain_hospital_proto_hospital_proto_msgTypes,
	}.Build()
	File_domain_hospital_proto_hospital_proto = out.File
	file_domain_hospital_proto_hospital_proto_rawDesc = nil
	file_domain_hospital_proto_hospital_proto_goTypes = nil
	file_domain_hospital_proto_hospital_proto_depIdxs = nil
}
